baseurl = "/"
title = "Donald Schulz"
theme = "hugo-theme-nix2"
languageCode = "en-us"
disqusShortname = "your_disqus_shortname"

[menu]
  [[menu.header]]
    name = "post"
    weight = 0
    url = "post"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "about"

[params]
  GithubID = "SchulzDL"
  TwitterID = "donaldlschulz"
  LinkedInID = "your_linkedin"
  MediumID = ""
  SpotifyID = ""
  SoundcloudID = "thunderfoot-430950952"
  YoutubeID = ""
  TelegramID = ""
  InstagramID = ""
  FacebookID = ""
  Name = "The Donald Schulz Project"
  HeaderUsername = "hugo"
  HeaderHostname = "gohugo.io"
  Email = "donald@schulz.com"
  About = "Hi I'm Donald and this is my web site where I like to share the new music that I am working on and provide some background on the songs I am releasing. Enjoy!"
  ProfilePicture = "logo.png"
  Favicon = "favicon.ico"
  BlogOnIndex = true

