baseurl = "http://example.org/"
title = "Hugo Website"
theme = "hugo-theme-nix"
languageCode = "en-us"
disqusShortname = "your_disqus_shortname"

[menu]
  [[menu.header]]
    name = "post"
    weight = 0
    url = "post"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "about"

[params]
  GithubID = "your_github"
  TwitterID = "your_twitter"
  LinkedInID = "your_linkedin"
  MediumID = "your_medium"
  SpotifyID = "your_spotify"
  SoundcloudID = "your_soundcloud"
  YoutubeID = "your_youtube"
  TelegramID = "your_telegram"
  Name = "The Donald Schulz Project"
  HeaderUsername = "hugo"
  HeaderHostname = "gohugo.io"
  Email = "donald@schulz.com"
  About = "Hi I'm Donald and this is my web site where I like to share the new music that I am working on and provide some background on the songs I am releasing. Enjoy!"
  ProfilePicture = "/donald.png"
  Favicon = "/favicon.ico"
  BlogOnIndex = true

